Veneziano Milestone 3

Cleaning/Formatting Website Data

Step #1: Scraping the data

In [4]:
import pandas as pd

# read the HTML tables from the website

url = "https://en.wikipedia.org/wiki/List_of_countries_by_life_expectancy"
tables = pd.read_html(url)

# display the number of tables in the dataset and inspect their content
print(f"Number of tables found: {len(tables)}")

# display the first few rows of each table sto find the correct one
for i, table in enumerate(tables):
    print(f"Table {i}:")
    print(table.head())
    print("\n")

Number of tables found: 13
Table 0:
                                                   0  \
0  ⩾ 84 82.00–83.99 80.00–81.99 78.00–79.99 76.00...

                                                   1  \
0  72.00–73.99 70.00–71.99 68.00–69.99 66.00–67.9...

                                                 2
0  60.00–61.99 58.00–59.99 56.00–57.99 54.00–55.99


Table 1:
  Countries and territories Life expectancy for population in general  \
  Countries and territories                                  at birth
0                 Hong Kong                                     85.51
1                     Japan                                     84.71
2               South Korea                                     84.33
3          French Polynesia                                     84.07
4                   Andorra                                     84.04

                                                           \
  bonus 0→15  at 15 bonus 15→65  at 65 bonus 65→80  at 80
0       0.21  70.72        2.47  23.19        3.27  11.45
1       0.24  69.96        2.54  22.49        3.45  10.95
2       0.30  69.63        1.69  21.32        4.14  10.45
3       0.58  69.65        1.85  21.50        3.72  10.23
4       0.58  69.62        1.85  21.47        3.72  10.19

  Life expectancy for male         ...        Life expectancy for female  \
                  at birth  at 15  ...  at 80                   at birth
0                    82.84  68.06  ...  10.26                      88.13
1                    81.69  66.93  ...   9.27                      87.74
2                    81.19  66.51  ...   8.40                      87.16
3                    81.78  67.37  ...   8.88                      86.50
4                    82.10  67.68  ...   9.03                      86.11

                        Sex gap                   Unnamed: 20_level_0
   at 15  at 65  at 80 at birth at 15 at 65 at 80 Unnamed: 20_level_1
0  73.33  25.21  12.54     5.29  5.27  4.00  2.27                 NaN
1  72.98  24.85  12.20     6.05  6.05  4.87  2.93                 NaN
2  72.44  23.55  11.68     5.96  5.93  4.92  3.27                 NaN
3  72.07  23.48  11.37     4.73  4.70  3.90  2.48                 NaN
4  71.70  23.18  11.16     4.01  4.02  3.36  2.13                 NaN

[5 rows x 21 columns]


Table 2:
  Countries and territories   2023                       Historical data  \
  Countries and territories    All   Male Female Sex gap            2019
0          Hong Kong, China  85.51  82.84  88.13    5.29           85.26
1                     Japan  84.71  81.69  87.74    6.05           84.42
2               South Korea  84.33  81.19  87.16    5.96           83.69
3          French Polynesia  84.07  81.78  86.50    4.73           83.19
4                   Andorra  84.04  82.10  86.11    4.01           84.10

                                                                           \
  2019 →2020   2020 2020 →2021   2021 2021 →2022   2022 2022 →2023   2023
0      −0.56  84.71       0.38  85.08      −1.60  83.48       2.03  85.51
1       0.25  84.67      −0.12  84.55      −0.50  84.05       0.66  84.71
2      −0.01  83.67       0.18  83.85      −1.12  82.73       1.60  84.33
3      −0.74  82.46      −2.89  79.57       4.29  83.86       0.21  84.07
4      −4.68  79.42       2.91  82.33       1.69  84.02       0.03  84.04

  Recovery from COVID-19: 2019→2023 Unnamed: 15_level_0
  Recovery from COVID-19: 2019→2023 Unnamed: 15_level_1
0                              0.25                 NaN
1                              0.29                 NaN
2                              0.64                 NaN
3                              0.88                 NaN
4                             −0.06                 NaN


Table 3:
  Countries and territories   2022                       Historical data  \
  Countries and territories    All   Male Female Sex gap            2014
0          Macao SAR, China  85.38  82.75  87.98    5.23           83.88
1                     Japan  84.00  81.05  87.09    6.04           83.59
2      Hong Kong SAR, China  83.66  80.70  86.77    6.07           83.94
3          French Polynesia  83.55  81.33  85.98    4.65           82.21
4               Switzerland  83.45  81.60  85.40    3.80           83.20

                                                                           \
  2014 →2019   2019 2019 →2020   2020 2020 →2021   2021 2021 →2022   2022
0       1.09  84.98       0.21  85.18       0.22  85.40      −0.02  85.38
1       0.77  84.36       0.20  84.56      −0.11  84.45      −0.45  84.00
2       1.22  85.16       0.34  85.50       0.04  85.53      −1.87  83.66
3       0.78  83.00      −0.78  82.22      −2.73  79.49       4.06  83.55
4       0.71  83.90      −0.90  83.00       0.75  83.75      −0.30  83.45

  recovery from COVID-19: 2019→2022 Unnamed: 15_level_0
  recovery from COVID-19: 2019→2022 Unnamed: 15_level_1
0                              0.40                 NaN
1                             −0.36                 NaN
2                             −1.49                 NaN
3                              0.55                 NaN
4                             −0.45                 NaN


Table 4:
     Countries Life expectancy at birth                         HALE at birth  \
     Countries                      All     M     F  FΔM Δ 2000           All
0        Japan                     84.3  81.5  86.9  5.4    3.2          74.1
1  Switzerland                     83.4  81.8  85.1  3.3    3.7          72.5
2  South Korea                     83.3  80.3  86.1  5.8    7.1          73.1
3    Singapore                     83.2  81.0  85.5  4.5    4.8          73.6
4        Spain                     83.2  80.7  85.7  5.0    4.1          72.1

                    ... Life expectancy at age 60                          \
      M     F  FΔM  ...                       All     M     F  FΔM Δ 2000
0  72.6  75.5  2.9  ...                      26.3  23.9  28.6  4.7    2.2
1  72.2  72.8  0.6  ...                      25.4  24.1  26.6  2.5    2.4
2  71.3  74.7  3.4  ...                      25.8  23.4  27.9  4.5    5.1
3  72.4  74.7  2.3  ...                      25.5  23.8  27.2  3.4    4.0
4  71.3  72.9  1.6  ...                      25.4  23.3  27.3  4.0    2.7

  HALE at age 60
             All     M     F  FΔM Δ 2000
0           20.4  18.8  21.8  3.0    1.7
1           19.5  18.8  20.2  1.4    1.8
2           19.8  18.2  21.2  3.0    3.9
3           20.0  18.8  21.0  2.2    3.4
4           19.2  18.0  20.3  2.3    1.9

[5 rows x 21 columns]


Table 5:
      Country    All      M      F  Sex gap
0      Monaco  89.60  85.70  93.49     7.79
1   Singapore  86.43  83.65  89.20     5.55
2       Macau  85.06  82.09  88.02     5.93
3       Japan  84.91  81.92  87.90     5.98
4  San Marino  83.86  81.30  86.65     5.35


Table 6:
       Country 2022 overall 2022 male 2022 female 2022 FΔM  2019 2019 →2020  \
0        Japan            —         —           —        —  84.4        0.2
1  Switzerland         83.5      81.6        85.4      3.8  84.0       −0.9
2        Spain         83.2      80.4        85.9      5.5  84.0       −1.6
3        Italy         83.0      80.9        85.0      4.1  83.6       −1.3
4  South Korea            —         —           —        —  83.3        0.2

   2020 2020 →2021  2021 2021 →2022  2022 2019 →2022
0  84.6       −0.1  84.5          —     —          —
1  83.1        0.8  83.9       −0.4  83.5       −0.5
2  82.4        0.9  83.3       −0.1  83.2       −0.8
3  82.3        0.4  82.7        0.3  83.0       −0.6
4  83.5        0.1  83.6          —     —          —


Table 7:
                    0                        1                        2  \
0  ≥ 80.0 75.0 – 79.9  70.0 – 74.9 65.0 – 69.9  60.0 – 64.9 55.0 – 59.9

                3
0  < 55.0 no data


Table 8:
                    0                        1                        2  \
0  ≥ 85.0 80.0 – 84.9  75.0 – 79.9 70.0 – 74.9  65.0 – 69.9 60.0 – 64.9

                3
0  < 60.0 no data


Table 9:
  vteLists of countries by quality of life rankings  \
0                                           General
1                                          Economic
2                                       Environment
3                                            Health
4                                  Social/political

  vteLists of countries by quality of life rankings.1
0  Life expectancy Africa Asia Europe North Ameri...
1  Net take-home pay Long-term unemployment rate ...
2  Greenhouse gas emissions per capita Dashboard ...
3  Air pollution Antidepressant use Cancer rate C...
4  Corruption Perceptions Index Democracy indices...


Table 10:
  vteLists of countries by population statistics  \
0                                         Global
1                          Continents/subregions
2                               Intercontinental
3                             Cities/urban areas
4                                Past and future

    vteLists of countries by population statistics.1
0  Current population United Nations Demographics...
1  Africa Antarctica Asia Europe North America Ca...
2  Americas Arab world Commonwealth of Nations Eu...
3  World cities National capitals Megacities Mega...
4  Past and future population World population es...


Table 11:
               vteLongevity                                     vteLongevity.1
0                    Ageing  Old age Longevity myths Senescence aging-assoc...
1            Life extension  Topic outline index Anti-aging movement Biodem...
2  Lists of life expectancy  by country World Africa Americas North America...
3                by country  World Africa Americas North America South Amer...
4      regions of countries  Argentina Australia Belgium Brazil Canada Chin...


Table 12:
                       0                                                  1
0             by country  World Africa Americas North America South Amer...
1   regions of countries  Argentina Australia Belgium Brazil Canada Chin...
2  regions by continents           Africa Asia Europe Oceania South America

Explantation: This code reads all HTML tables from the website and prints the first few rows of each table, so I can visually inspect and choose the correct ones.

Step # 2 Load the relevant tables

In [8]:
# load tables 1, 2, 3 and 5
df1 = tables[1]
df2 = tables[2]
df3 = tables[3]
df5 = tables[5]

# display the first few row of each table
print("Table 1:")
print(df1.head())
print("\nTable 2:")
print(df2.head())
print("\nTable 3:")
print(df3.head())
print("\nTable 5:")
print(df5.head())

Table 1:
  Countries and territories Life expectancy for population in general  \
  Countries and territories                                  at birth
0                 Hong Kong                                     85.51
1                     Japan                                     84.71
2               South Korea                                     84.33
3          French Polynesia                                     84.07
4                   Andorra                                     84.04

                                                           \
  bonus 0→15  at 15 bonus 15→65  at 65 bonus 65→80  at 80
0       0.21  70.72        2.47  23.19        3.27  11.45
1       0.24  69.96        2.54  22.49        3.45  10.95
2       0.30  69.63        1.69  21.32        4.14  10.45
3       0.58  69.65        1.85  21.50        3.72  10.23
4       0.58  69.62        1.85  21.47        3.72  10.19

  Life expectancy for male         ...        Life expectancy for female  \
                  at birth  at 15  ...  at 80                   at birth
0                    82.84  68.06  ...  10.26                      88.13
1                    81.69  66.93  ...   9.27                      87.74
2                    81.19  66.51  ...   8.40                      87.16
3                    81.78  67.37  ...   8.88                      86.50
4                    82.10  67.68  ...   9.03                      86.11

                        Sex gap                   Unnamed: 20_level_0
   at 15  at 65  at 80 at birth at 15 at 65 at 80 Unnamed: 20_level_1
0  73.33  25.21  12.54     5.29  5.27  4.00  2.27                 NaN
1  72.98  24.85  12.20     6.05  6.05  4.87  2.93                 NaN
2  72.44  23.55  11.68     5.96  5.93  4.92  3.27                 NaN
3  72.07  23.48  11.37     4.73  4.70  3.90  2.48                 NaN
4  71.70  23.18  11.16     4.01  4.02  3.36  2.13                 NaN

[5 rows x 21 columns]

Table 2:
  Countries and territories   2023                       Historical data  \
  Countries and territories    All   Male Female Sex gap            2019
0          Hong Kong, China  85.51  82.84  88.13    5.29           85.26
1                     Japan  84.71  81.69  87.74    6.05           84.42
2               South Korea  84.33  81.19  87.16    5.96           83.69
3          French Polynesia  84.07  81.78  86.50    4.73           83.19
4                   Andorra  84.04  82.10  86.11    4.01           84.10

                                                                           \
  2019 →2020   2020 2020 →2021   2021 2021 →2022   2022 2022 →2023   2023
0      −0.56  84.71       0.38  85.08      −1.60  83.48       2.03  85.51
1       0.25  84.67      −0.12  84.55      −0.50  84.05       0.66  84.71
2      −0.01  83.67       0.18  83.85      −1.12  82.73       1.60  84.33
3      −0.74  82.46      −2.89  79.57       4.29  83.86       0.21  84.07
4      −4.68  79.42       2.91  82.33       1.69  84.02       0.03  84.04

  Recovery from COVID-19: 2019→2023 Unnamed: 15_level_0
  Recovery from COVID-19: 2019→2023 Unnamed: 15_level_1
0                              0.25                 NaN
1                              0.29                 NaN
2                              0.64                 NaN
3                              0.88                 NaN
4                             −0.06                 NaN

Table 3:
  Countries and territories   2022                       Historical data  \
  Countries and territories    All   Male Female Sex gap            2014
0          Macao SAR, China  85.38  82.75  87.98    5.23           83.88
1                     Japan  84.00  81.05  87.09    6.04           83.59
2      Hong Kong SAR, China  83.66  80.70  86.77    6.07           83.94
3          French Polynesia  83.55  81.33  85.98    4.65           82.21
4               Switzerland  83.45  81.60  85.40    3.80           83.20

                                                                           \
  2014 →2019   2019 2019 →2020   2020 2020 →2021   2021 2021 →2022   2022
0       1.09  84.98       0.21  85.18       0.22  85.40      −0.02  85.38
1       0.77  84.36       0.20  84.56      −0.11  84.45      −0.45  84.00
2       1.22  85.16       0.34  85.50       0.04  85.53      −1.87  83.66
3       0.78  83.00      −0.78  82.22      −2.73  79.49       4.06  83.55
4       0.71  83.90      −0.90  83.00       0.75  83.75      −0.30  83.45

  recovery from COVID-19: 2019→2022 Unnamed: 15_level_0
  recovery from COVID-19: 2019→2022 Unnamed: 15_level_1
0                              0.40                 NaN
1                             −0.36                 NaN
2                             −1.49                 NaN
3                              0.55                 NaN
4                             −0.45                 NaN

Table 5:
      Country    All      M      F  Sex gap
0      Monaco  89.60  85.70  93.49     7.79
1   Singapore  86.43  83.65  89.20     5.55
2       Macau  85.06  82.09  88.02     5.93
3       Japan  84.91  81.92  87.90     5.98
4  San Marino  83.86  81.30  86.65     5.35

Explanation: I loaded the four relevant tables (1, 2, 3, and 5) and displayed the first few rows of each to verify their structure before proceeding with the cleaning and transformation process.

Step 3: Check the number of columns before renaming

In [12]:
# check the number of columns for each table to understand their structure
print(f"df1 has {len(df1.columns)} columns")
print(f"df2 has {len(df2.columns)} columns")
print(f"df3 has {len(df3.columns)} columns")
print(f"df5 has {len(df5.columns)} columns")

# display the columns for each table to see their structure
print(df1.columns)
print(df2.columns)
print(df3.columns)
print(df5.columns)

df1 has 21 columns
df2 has 16 columns
df3 has 16 columns
df5 has 5 columns
MultiIndex([(                'Countries and territories', ...),
            ('Life expectancy for population in general', ...),
            ('Life expectancy for population in general', ...),
            ('Life expectancy for population in general', ...),
            ('Life expectancy for population in general', ...),
            ('Life expectancy for population in general', ...),
            ('Life expectancy for population in general', ...),
            ('Life expectancy for population in general', ...),
            (                 'Life expectancy for male', ...),
            (                 'Life expectancy for male', ...),
            (                 'Life expectancy for male', ...),
            (                 'Life expectancy for male', ...),
            (               'Life expectancy for female', ...),
            (               'Life expectancy for female', ...),
            (               'Life expectancy for female', ...),
            (               'Life expectancy for female', ...),
            (                                  'Sex gap', ...),
            (                                  'Sex gap', ...),
            (                                  'Sex gap', ...),
            (                                  'Sex gap', ...),
            (                      'Unnamed: 20_level_0', ...)],
           )
MultiIndex([(        'Countries and territories', ...),
            (                             '2023', ...),
            (                             '2023', ...),
            (                             '2023', ...),
            (                             '2023', ...),
            (                  'Historical data', ...),
            (                  'Historical data', ...),
            (                  'Historical data', ...),
            (                  'Historical data', ...),
            (                  'Historical data', ...),
            (                  'Historical data', ...),
            (                  'Historical data', ...),
            (                  'Historical data', ...),
            (                  'Historical data', ...),
            ('Recovery from COVID-19: 2019→2023', ...),
            (              'Unnamed: 15_level_0', ...)],
           )
MultiIndex([(        'Countries and territories', ...),
            (                             '2022', ...),
            (                             '2022', ...),
            (                             '2022', ...),
            (                             '2022', ...),
            (                  'Historical data', ...),
            (                  'Historical data', ...),
            (                  'Historical data', ...),
            (                  'Historical data', ...),
            (                  'Historical data', ...),
            (                  'Historical data', ...),
            (                  'Historical data', ...),
            (                  'Historical data', ...),
            (                  'Historical data', ...),
            ('recovery from COVID-19: 2019→2022', ...),
            (              'Unnamed: 15_level_0', ...)],
           )
Index(['Country', 'All', 'M', 'F', 'Sex gap'], dtype='object')

Explanation: This code will help me verify the number of columns in each table, so I can rename the columns accurately.

Step 4: Flatten Multiindex Columns and Display Columns

In [16]:
# function to flatten MultiIndex columns for tables 1, 2 and 3
def flatten_columns(df, table_name):
    if isinstance(df.columns, pd.MultiIndex):
        df.columns = [' '.join(col).strip() for col in df.columns.values]
        print(f"MultiIndex columns flattened for {table_name}")
    else:
        print(f"No MultiIndex found in {table_name}")
        
# flatten the columns for tables with MultiIndex
flatten_columns(df1, 'Table 1')
flatten_columns(df2, 'Table 2')
flatten_columns(df3, 'Table 3')

# print the flattened columns
print("\nTable 1 columns:")
print(df1.columns)
print("\nTable 2 columns:")
print(df2.columns)
print("\nTable 3 columns:")
print(df3.columns)

MultiIndex columns flattened for Table 1
MultiIndex columns flattened for Table 2
MultiIndex columns flattened for Table 3

Table 1 columns:
Index(['Countries and territories Countries and territories',
       'Life expectancy for population in general at birth',
       'Life expectancy for population in general bonus 0→15',
       'Life expectancy for population in general at 15',
       'Life expectancy for population in general bonus 15→65',
       'Life expectancy for population in general at 65',
       'Life expectancy for population in general bonus 65→80',
       'Life expectancy for population in general at 80',
       'Life expectancy for male at birth', 'Life expectancy for male at 15',
       'Life expectancy for male at 65', 'Life expectancy for male at 80',
       'Life expectancy for female at birth',
       'Life expectancy for female at 15', 'Life expectancy for female at 65',
       'Life expectancy for female at 80', 'Sex gap at birth', 'Sex gap at 15',
       'Sex gap at 65', 'Sex gap at 80',
       'Unnamed: 20_level_0 Unnamed: 20_level_1'],
      dtype='object')

Table 2 columns:
Index(['Countries and territories Countries and territories', '2023 All',
       '2023 Male', '2023 Female', '2023 Sex gap', 'Historical data 2019',
       'Historical data 2019 →2020', 'Historical data 2020',
       'Historical data 2020 →2021', 'Historical data 2021',
       'Historical data 2021 →2022', 'Historical data 2022',
       'Historical data 2022 →2023', 'Historical data 2023',
       'Recovery from COVID-19: 2019→2023 Recovery from COVID-19: 2019→2023',
       'Unnamed: 15_level_0 Unnamed: 15_level_1'],
      dtype='object')

Table 3 columns:
Index(['Countries and territories Countries and territories', '2022 All',
       '2022 Male', '2022 Female', '2022 Sex gap', 'Historical data 2014',
       'Historical data 2014 →2019', 'Historical data 2019',
       'Historical data 2019 →2020', 'Historical data 2020',
       'Historical data 2020 →2021', 'Historical data 2021',
       'Historical data 2021 →2022', 'Historical data 2022',
       'recovery from COVID-19: 2019→2022 recovery from COVID-19: 2019→2022',
       'Unnamed: 15_level_0 Unnamed: 15_level_1'],
      dtype='object')

Explanation: This code flattens the MultiIndex columns in df1, df2, and df3 by joining the column levels with a space. It then prints the columns for verification to ensure they are properly flattened.

Step 5: Check column names

In [20]:
# Check the columns names for each table
print(df1.columns)
print(df2.columns)
print(df3.columns)
print(df5.columns)

Index(['Countries and territories Countries and territories',
       'Life expectancy for population in general at birth',
       'Life expectancy for population in general bonus 0→15',
       'Life expectancy for population in general at 15',
       'Life expectancy for population in general bonus 15→65',
       'Life expectancy for population in general at 65',
       'Life expectancy for population in general bonus 65→80',
       'Life expectancy for population in general at 80',
       'Life expectancy for male at birth', 'Life expectancy for male at 15',
       'Life expectancy for male at 65', 'Life expectancy for male at 80',
       'Life expectancy for female at birth',
       'Life expectancy for female at 15', 'Life expectancy for female at 65',
       'Life expectancy for female at 80', 'Sex gap at birth', 'Sex gap at 15',
       'Sex gap at 65', 'Sex gap at 80',
       'Unnamed: 20_level_0 Unnamed: 20_level_1'],
      dtype='object')
Index(['Countries and territories Countries and territories', '2023 All',
       '2023 Male', '2023 Female', '2023 Sex gap', 'Historical data 2019',
       'Historical data 2019 →2020', 'Historical data 2020',
       'Historical data 2020 →2021', 'Historical data 2021',
       'Historical data 2021 →2022', 'Historical data 2022',
       'Historical data 2022 →2023', 'Historical data 2023',
       'Recovery from COVID-19: 2019→2023 Recovery from COVID-19: 2019→2023',
       'Unnamed: 15_level_0 Unnamed: 15_level_1'],
      dtype='object')
Index(['Countries and territories Countries and territories', '2022 All',
       '2022 Male', '2022 Female', '2022 Sex gap', 'Historical data 2014',
       'Historical data 2014 →2019', 'Historical data 2019',
       'Historical data 2019 →2020', 'Historical data 2020',
       'Historical data 2020 →2021', 'Historical data 2021',
       'Historical data 2021 →2022', 'Historical data 2022',
       'recovery from COVID-19: 2019→2022 recovery from COVID-19: 2019→2022',
       'Unnamed: 15_level_0 Unnamed: 15_level_1'],
      dtype='object')
Index(['Country', 'All', 'M', 'F', 'Sex gap'], dtype='object')

Step # 6: Check for extra spaces in column names

In [23]:
# define a function to check for extra spaces in the column names
def check_column_spaces(df, table_name):
    for col in df.columns:
        if ' ' in ''.join(col):
            print(f"Extra spaces found in column: '{col}' in {table_name}")

# apply the check to each table
tables_to_check = {
    'Table 1': df1,
    'Table 2': df2,
    'Table 3': df3,
    'Table 5': df5
}

# iterate through each table and check for extra spaces
for table_name, df in tables_to_check.items():
    print(f"\nChecking {table_name} for extra spaces in column names:")
    check_column_spaces(df, table_name)

Checking Table 1 for extra spaces in column names:
Extra spaces found in column: 'Countries and territories Countries and territories' in Table 1
Extra spaces found in column: 'Life expectancy for population in general at birth' in Table 1
Extra spaces found in column: 'Life expectancy for population in general bonus 0→15' in Table 1
Extra spaces found in column: 'Life expectancy for population in general at 15' in Table 1
Extra spaces found in column: 'Life expectancy for population in general bonus 15→65' in Table 1
Extra spaces found in column: 'Life expectancy for population in general at 65' in Table 1
Extra spaces found in column: 'Life expectancy for population in general bonus 65→80' in Table 1
Extra spaces found in column: 'Life expectancy for population in general at 80' in Table 1
Extra spaces found in column: 'Life expectancy for male at birth' in Table 1
Extra spaces found in column: 'Life expectancy for male at 15' in Table 1
Extra spaces found in column: 'Life expectancy for male at 65' in Table 1
Extra spaces found in column: 'Life expectancy for male at 80' in Table 1
Extra spaces found in column: 'Life expectancy for female at birth' in Table 1
Extra spaces found in column: 'Life expectancy for female at 15' in Table 1
Extra spaces found in column: 'Life expectancy for female at 65' in Table 1
Extra spaces found in column: 'Life expectancy for female at 80' in Table 1
Extra spaces found in column: 'Sex gap at birth' in Table 1
Extra spaces found in column: 'Sex gap at 15' in Table 1
Extra spaces found in column: 'Sex gap at 65' in Table 1
Extra spaces found in column: 'Sex gap at 80' in Table 1
Extra spaces found in column: 'Unnamed: 20_level_0 Unnamed: 20_level_1' in Table 1

Checking Table 2 for extra spaces in column names:
Extra spaces found in column: 'Countries and territories Countries and territories' in Table 2
Extra spaces found in column: '2023 All' in Table 2
Extra spaces found in column: '2023 Male' in Table 2
Extra spaces found in column: '2023 Female' in Table 2
Extra spaces found in column: '2023 Sex gap' in Table 2
Extra spaces found in column: 'Historical data 2019' in Table 2
Extra spaces found in column: 'Historical data 2019 →2020' in Table 2
Extra spaces found in column: 'Historical data 2020' in Table 2
Extra spaces found in column: 'Historical data 2020 →2021' in Table 2
Extra spaces found in column: 'Historical data 2021' in Table 2
Extra spaces found in column: 'Historical data 2021 →2022' in Table 2
Extra spaces found in column: 'Historical data 2022' in Table 2
Extra spaces found in column: 'Historical data 2022 →2023' in Table 2
Extra spaces found in column: 'Historical data 2023' in Table 2
Extra spaces found in column: 'Recovery from COVID-19: 2019→2023 Recovery from COVID-19: 2019→2023' in Table 2
Extra spaces found in column: 'Unnamed: 15_level_0 Unnamed: 15_level_1' in Table 2

Checking Table 3 for extra spaces in column names:
Extra spaces found in column: 'Countries and territories Countries and territories' in Table 3
Extra spaces found in column: '2022 All' in Table 3
Extra spaces found in column: '2022 Male' in Table 3
Extra spaces found in column: '2022 Female' in Table 3
Extra spaces found in column: '2022 Sex gap' in Table 3
Extra spaces found in column: 'Historical data 2014' in Table 3
Extra spaces found in column: 'Historical data 2014 →2019' in Table 3
Extra spaces found in column: 'Historical data 2019' in Table 3
Extra spaces found in column: 'Historical data 2019 →2020' in Table 3
Extra spaces found in column: 'Historical data 2020' in Table 3
Extra spaces found in column: 'Historical data 2020 →2021' in Table 3
Extra spaces found in column: 'Historical data 2021' in Table 3
Extra spaces found in column: 'Historical data 2021 →2022' in Table 3
Extra spaces found in column: 'Historical data 2022' in Table 3
Extra spaces found in column: 'recovery from COVID-19: 2019→2022 recovery from COVID-19: 2019→2022' in Table 3
Extra spaces found in column: 'Unnamed: 15_level_0 Unnamed: 15_level_1' in Table 3

Checking Table 5 for extra spaces in column names:
Extra spaces found in column: 'Sex gap' in Table 5

Explanation: This code will help me identify whether extra spaces are present in any of the tables column names.

Step # 7: Remove extra spaces from column names

In [27]:
# define a function to remove extra spaces from column names
def remove_column_spaces(df, table_name):
    df.columns = [col.strip() for col in df.columns]
    print(f"Extra spaces removed from columns names in {table_name}")

# apply the function to each table that has extra spaces
tables_to_fix = {
    'Table 1': df1,
    'Table 2': df2,
    'Table 3': df3,
    'Table 5': df5
}

# iterate through each table and remove extra spaces
for table_name, df in tables_to_fix.items():
    print(f"\nFixing {table_name}:")
    remove_column_spaces(df, table_name)

# display the updated column names
for table_name, df in tables_to_fix.items():
    print(df.columns)

Fixing Table 1:
Extra spaces removed from columns names in Table 1

Fixing Table 2:
Extra spaces removed from columns names in Table 2

Fixing Table 3:
Extra spaces removed from columns names in Table 3

Fixing Table 5:
Extra spaces removed from columns names in Table 5
Index(['Countries and territories Countries and territories',
       'Life expectancy for population in general at birth',
       'Life expectancy for population in general bonus 0→15',
       'Life expectancy for population in general at 15',
       'Life expectancy for population in general bonus 15→65',
       'Life expectancy for population in general at 65',
       'Life expectancy for population in general bonus 65→80',
       'Life expectancy for population in general at 80',
       'Life expectancy for male at birth', 'Life expectancy for male at 15',
       'Life expectancy for male at 65', 'Life expectancy for male at 80',
       'Life expectancy for female at birth',
       'Life expectancy for female at 15', 'Life expectancy for female at 65',
       'Life expectancy for female at 80', 'Sex gap at birth', 'Sex gap at 15',
       'Sex gap at 65', 'Sex gap at 80',
       'Unnamed: 20_level_0 Unnamed: 20_level_1'],
      dtype='object')
Index(['Countries and territories Countries and territories', '2023 All',
       '2023 Male', '2023 Female', '2023 Sex gap', 'Historical data 2019',
       'Historical data 2019 →2020', 'Historical data 2020',
       'Historical data 2020 →2021', 'Historical data 2021',
       'Historical data 2021 →2022', 'Historical data 2022',
       'Historical data 2022 →2023', 'Historical data 2023',
       'Recovery from COVID-19: 2019→2023 Recovery from COVID-19: 2019→2023',
       'Unnamed: 15_level_0 Unnamed: 15_level_1'],
      dtype='object')
Index(['Countries and territories Countries and territories', '2022 All',
       '2022 Male', '2022 Female', '2022 Sex gap', 'Historical data 2014',
       'Historical data 2014 →2019', 'Historical data 2019',
       'Historical data 2019 →2020', 'Historical data 2020',
       'Historical data 2020 →2021', 'Historical data 2021',
       'Historical data 2021 →2022', 'Historical data 2022',
       'recovery from COVID-19: 2019→2022 recovery from COVID-19: 2019→2022',
       'Unnamed: 15_level_0 Unnamed: 15_level_1'],
      dtype='object')
Index(['Country', 'All', 'M', 'F', 'Sex gap'], dtype='object')

Explanation: This code removes extra spaces from the column names in each table and then shows the updated names to check if they are fixed.

Step 8: Check the number of columns in each table before renaming them

In [31]:
print(f"df1 has {len(df1.columns)} columns")
print(f"df2 has {len(df2.columns)} columns")
print(f"df3 has {len(df3.columns)} columns")
print(f"df5 has {len(df5.columns)} columns")

df1 has 21 columns
df2 has 16 columns
df3 has 16 columns
df5 has 5 columns

Step 9: Rename columns for each table

In [34]:
# For df1 (21 columns)
df1.columns = ['Country', 'Life Expectancy Both Sexes at Birth', 'Life Expectancy Bonus 0→15', 
               'Life Expectancy at 15', 'Life Expectancy Bonus 15→65', 'Life Expectancy at 65', 
               'Life Expectancy Bonus 65→80', 'Life Expectancy at 80', 'Male Life Expectancy at Birth', 
               'Male Life Expectancy at 15', 'Male Life Expectancy at 65', 'Male Life Expectancy at 80', 
               'Female Life Expectancy at Birth', 'Female Life Expectancy at 15', 'Female Life Expectancy at 65', 
               'Female Life Expectancy at 80', 'Sex Gap at Birth', 'Sex Gap at 15', 'Sex Gap at 65', 
               'Sex Gap at 80', 'Unnamed']

# For df2 (16 columns)
df2.columns = ['Country', '2023 Life Expectancy All', '2023 Male', '2023 Female', '2023 Sex Gap', 
               'Historical Life Expectancy 2019', '2019 → 2020 Change', 'Historical Life Expectancy 2020', 
               '2020 → 2021 Change', 'Historical Life Expectancy 2021', '2021 → 2022 Change', 
               'Historical Life Expectancy 2022', '2022 → 2023 Change', 'Historical Life Expectancy 2023', 
               'Recovery from COVID-19', 'Unnamed']

# For df3 (16 columns)
df3.columns = ['Country', '2022 Life Expectancy All', '2022 Male', '2022 Female', '2022 Sex Gap', 
               'Historical Life Expectancy 2014', '2014 → 2019 Change', 'Historical Life Expectancy 2019', 
               '2019 → 2020 Change', 'Historical Life Expectancy 2020', '2020 → 2021 Change', 
               'Historical Life Expectancy 2021', '2021 → 2022 Change', 'Historical Life Expectancy 2022', 
               'Recovery from COVID-19', 'Unnamed']

# For df5 (5 columns)
df5.columns = ['Country', 'Life Expectancy All', 'Male', 'Female', 'Sex Gap']

# Verify the renamed columns
print(df1.columns)
print(df2.columns)
print(df3.columns)
print(df5.columns)

Index(['Country', 'Life Expectancy Both Sexes at Birth',
       'Life Expectancy Bonus 0→15', 'Life Expectancy at 15',
       'Life Expectancy Bonus 15→65', 'Life Expectancy at 65',
       'Life Expectancy Bonus 65→80', 'Life Expectancy at 80',
       'Male Life Expectancy at Birth', 'Male Life Expectancy at 15',
       'Male Life Expectancy at 65', 'Male Life Expectancy at 80',
       'Female Life Expectancy at Birth', 'Female Life Expectancy at 15',
       'Female Life Expectancy at 65', 'Female Life Expectancy at 80',
       'Sex Gap at Birth', 'Sex Gap at 15', 'Sex Gap at 65', 'Sex Gap at 80',
       'Unnamed'],
      dtype='object')
Index(['Country', '2023 Life Expectancy All', '2023 Male', '2023 Female',
       '2023 Sex Gap', 'Historical Life Expectancy 2019', '2019 → 2020 Change',
       'Historical Life Expectancy 2020', '2020 → 2021 Change',
       'Historical Life Expectancy 2021', '2021 → 2022 Change',
       'Historical Life Expectancy 2022', '2022 → 2023 Change',
       'Historical Life Expectancy 2023', 'Recovery from COVID-19', 'Unnamed'],
      dtype='object')
Index(['Country', '2022 Life Expectancy All', '2022 Male', '2022 Female',
       '2022 Sex Gap', 'Historical Life Expectancy 2014', '2014 → 2019 Change',
       'Historical Life Expectancy 2019', '2019 → 2020 Change',
       'Historical Life Expectancy 2020', '2020 → 2021 Change',
       'Historical Life Expectancy 2021', '2021 → 2022 Change',
       'Historical Life Expectancy 2022', 'Recovery from COVID-19', 'Unnamed'],
      dtype='object')
Index(['Country', 'Life Expectancy All', 'Male', 'Female', 'Sex Gap'], dtype='object')

Explanation: The code renames the columns in each table to make them more descriptive and consistent, ensuring the column names reflect the data they contain.

Step 10: Convert Relevant Columns to Numeric

In [41]:
def convert_to_numeric(df, numeric_columns):
    for col in numeric_columns:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors='coerce') # convert and handle errors
            
# apply conversion to relevant numeric columns 
# for df1 (21 columns)
numeric_columns_df1 = ['Life Expectancy Both Sexes at Birth', 'Life Expectancy Bonus 0→15', 'Life Expectancy at 15',
                       'Life Expectancy Bonus 15→65', 'Life Expectancy at 65', 'Life Expectancy Bonus 65→80',
                       'Life Expectancy at 80', 'Male Life Expectancy at Birth', 'Male Life Expectancy at 15',
                       'Male Life Expectancy at 65', 'Male Life Expectancy at 80', 'Female Life Expectancy at Birth',
                       'Female Life Expectancy at 15', 'Female Life Expectancy at 65', 'Female Life Expectancy at 80',
                       'Sex Gap at Birth', 'Sex Gap at 15', 'Sex Gap at 65', 'Sex Gap at 80']
convert_to_numeric(df1, numeric_columns_df1)

# for df2 (16 columns)
numeric_columns_df2 = ['2023 Life Expectancy All', '2023 Male', '2023 Female', '2023 Sex Gap', 
                       'Historical Life Expectancy 2019', '2019 → 2020 Change', 'Historical Life Expectancy 2020',
                       '2020 → 2021 Change', 'Historical Life Expectancy 2021', '2021 → 2022 Change', 
                       'Historical Life Expectancy 2022', '2022 → 2023 Change', 'Historical Life Expectancy 2023']
convert_to_numeric(df2, numeric_columns_df2)

# For df3 (16 columns)
numeric_columns_df3 = ['2022 Life Expectancy All', '2022 Male', '2022 Female', '2022 Sex Gap',
                       'Historical Life Expectancy 2014', '2014 → 2019 Change', 'Historical Life Expectancy 2019',
                       '2019 → 2020 Change', 'Historical Life Expectancy 2020', '2020 → 2021 Change',
                       'Historical Life Expectancy 2021', '2021 → 2022 Change', 'Historical Life Expectancy 2022']
convert_to_numeric(df3, numeric_columns_df3)

# For df5 (5 columns)
numeric_columns_df5 = ['Life Expectancy All', 'Male', 'Female', 'Sex Gap']
convert_to_numeric(df5, numeric_columns_df5)

# print conversion
print(df1.dtypes)
print(df2.dtypes)
print(df3.dtypes)
print(df5.dtypes)

Country                                 object
Life Expectancy Both Sexes at Birth    float64
Life Expectancy Bonus 0→15             float64
Life Expectancy at 15                  float64
Life Expectancy Bonus 15→65            float64
Life Expectancy at 65                  float64
Life Expectancy Bonus 65→80            float64
Life Expectancy at 80                  float64
Male Life Expectancy at Birth          float64
Male Life Expectancy at 15             float64
Male Life Expectancy at 65             float64
Male Life Expectancy at 80             float64
Female Life Expectancy at Birth        float64
Female Life Expectancy at 15           float64
Female Life Expectancy at 65           float64
Female Life Expectancy at 80           float64
Sex Gap at Birth                       float64
Sex Gap at 15                          float64
Sex Gap at 65                          float64
Sex Gap at 80                          float64
Unnamed                                float64
dtype: object
Country                             object
2023 Life Expectancy All           float64
2023 Male                          float64
2023 Female                        float64
2023 Sex Gap                       float64
Historical Life Expectancy 2019    float64
2019 → 2020 Change                 float64
Historical Life Expectancy 2020    float64
2020 → 2021 Change                 float64
Historical Life Expectancy 2021    float64
2021 → 2022 Change                 float64
Historical Life Expectancy 2022    float64
2022 → 2023 Change                 float64
Historical Life Expectancy 2023    float64
Recovery from COVID-19              object
Unnamed                            float64
dtype: object
Country                             object
2022 Life Expectancy All           float64
2022 Male                          float64
2022 Female                        float64
2022 Sex Gap                       float64
Historical Life Expectancy 2014    float64
2014 → 2019 Change                 float64
Historical Life Expectancy 2019    float64
2019 → 2020 Change                 float64
Historical Life Expectancy 2020    float64
2020 → 2021 Change                 float64
Historical Life Expectancy 2021    float64
2021 → 2022 Change                 float64
Historical Life Expectancy 2022    float64
Recovery from COVID-19              object
Unnamed                            float64
dtype: object
Country                 object
Life Expectancy All    float64
Male                   float64
Female                 float64
Sex Gap                float64
dtype: object

Explanation: This step converts the relevant columns to numeric format using pd.to_numeric(), ensuring that any invalid values are handled by converting non-numeric entries into NaN for easier processing.

Step 11: Handle missing values

In [45]:
# fill the missing values with the median for numeric columns
def handle_missing_values(df, numeric_columns):
    for col in numeric_columns:
        if col in df.columns:
            df[col].fillna(df[col].median(), inplace=True) # fill NAN with median
        else:
            print(f"Column '{col}' not found in DataFrame")

# apply handling of missing values to numeric columns

handle_missing_values(df1, numeric_columns_df1)
handle_missing_values(df2, numeric_columns_df2)
handle_missing_values(df3, numeric_columns_df3)
handle_missing_values(df5, numeric_columns_df5)

Explanation: This step fills missing values in the numeric columns with the median value, ensuring data consistency for further analysis.

Step 12: Removing unnecessary columns if they exist

In [49]:
def remove_unnecessary_columns(df, columns_to_remove):
    for col in columns_to_remove:
        if col in df.columns:
            df.drop(columns=col, inplace=True)
        else:
            print(f"Column '{col}' not found in DataFrame.")

# apply to each dataframe
remove_unnecessary_columns(df1, ['Unnamed'])
remove_unnecessary_columns(df2, ['Unnamed'])
remove_unnecessary_columns(df3, ['Unnamed'])

Explanation: I used this code as a final check to confirm that the dataset is clean and that no irrelevant columns remain, ensuring consistency across all DataFrames before analysis.

In [52]:
# check column names to double check
print(df1.columns)
print(df2.columns)
print(df3.columns)
print(df5.columns)

Index(['Country', 'Life Expectancy Both Sexes at Birth',
       'Life Expectancy Bonus 0→15', 'Life Expectancy at 15',
       'Life Expectancy Bonus 15→65', 'Life Expectancy at 65',
       'Life Expectancy Bonus 65→80', 'Life Expectancy at 80',
       'Male Life Expectancy at Birth', 'Male Life Expectancy at 15',
       'Male Life Expectancy at 65', 'Male Life Expectancy at 80',
       'Female Life Expectancy at Birth', 'Female Life Expectancy at 15',
       'Female Life Expectancy at 65', 'Female Life Expectancy at 80',
       'Sex Gap at Birth', 'Sex Gap at 15', 'Sex Gap at 65', 'Sex Gap at 80'],
      dtype='object')
Index(['Country', '2023 Life Expectancy All', '2023 Male', '2023 Female',
       '2023 Sex Gap', 'Historical Life Expectancy 2019', '2019 → 2020 Change',
       'Historical Life Expectancy 2020', '2020 → 2021 Change',
       'Historical Life Expectancy 2021', '2021 → 2022 Change',
       'Historical Life Expectancy 2022', '2022 → 2023 Change',
       'Historical Life Expectancy 2023', 'Recovery from COVID-19'],
      dtype='object')
Index(['Country', '2022 Life Expectancy All', '2022 Male', '2022 Female',
       '2022 Sex Gap', 'Historical Life Expectancy 2014', '2014 → 2019 Change',
       'Historical Life Expectancy 2019', '2019 → 2020 Change',
       'Historical Life Expectancy 2020', '2020 → 2021 Change',
       'Historical Life Expectancy 2021', '2021 → 2022 Change',
       'Historical Life Expectancy 2022', 'Recovery from COVID-19'],
      dtype='object')
Index(['Country', 'Life Expectancy All', 'Male', 'Female', 'Sex Gap'], dtype='object')

During the process of cleaning and organizing the life expectancy data, several changes were made, such as renaming columns, converting numbers, filling in missing values with the median, and removing unnecessary columns. While these changes help improve the dataset’s usability, filling in missing values could lead to biased results, especially if certain countries had a lot of missing data. The data comes from Wikipedia, which is publicly available, but there are concerns about its accuracy, even though it references reliable sources like the World Bank and WHO. There could also be rules, like GDPR, about using health data responsibly. To avoid any ethical issues, it’s important to be transparent about any changes made and check the data against trustworthy sources. Additionally, the data should be used in ways that respect privacy and are compliant with any legal guidelines.

Print a human readable dataset

In [56]:
from IPython.display import display

# display the first frew rows of each cleaned dataframe
print("Cleaned df1:")
display(df1.head())

print("\nClenaed df2:")
display(df2.head())

print("n\Cleaned df3:")
display(df3.head())

print("n\Cleaned df5:")
display(df5.head())

Cleaned df1:

,Country,Life Expectancy Both Sexes at Birth,Life Expectancy Bonus 0→15,Life Expectancy at 15,Life Expectancy Bonus 15→65,Life Expectancy at 65,Life Expectancy Bonus 65→80,Life Expectancy at 80,Male Life Expectancy at Birth,Male Life Expectancy at 15,Male Life Expectancy at 65,Male Life Expectancy at 80,Female Life Expectancy at Birth,Female Life Expectancy at 15,Female Life Expectancy at 65,Female Life Expectancy at 80,Sex Gap at Birth,Sex Gap at 15,Sex Gap at 65,Sex Gap at 80
0,Hong Kong,85.51,0.21,70.72,2.47,23.19,3.27,11.45,82.84,68.06,21.21,10.26,88.13,73.33,25.21,12.54,5.29,5.27,4.00,2.27
1,Japan,84.71,0.24,69.96,2.54,22.49,3.45,10.95,81.69,66.93,19.98,9.27,87.74,72.98,24.85,12.20,6.05,6.05,4.87,2.93
2,South Korea,84.33,0.30,69.63,1.69,21.32,4.14,10.45,81.19,66.51,18.63,8.40,87.16,72.44,23.55,11.68,5.96,5.93,4.92,3.27
3,French Polynesia,84.07,0.58,69.65,1.85,21.50,3.72,10.23,81.78,67.37,19.58,8.88,86.50,72.07,23.48,11.37,4.73,4.70,3.90,2.48
4,Andorra,84.04,0.58,69.62,1.85,21.47,3.72,10.19,82.10,67.68,19.81,9.03,86.11,71.70,23.18,11.16,4.01,4.02,3.36,2.13

Clenaed df2:

,Country,2023 Life Expectancy All,2023 Male,2023 Female,2023 Sex Gap,Historical Life Expectancy 2019,2019 → 2020 Change,Historical Life Expectancy 2020,2020 → 2021 Change,Historical Life Expectancy 2021,2021 → 2022 Change,Historical Life Expectancy 2022,2022 → 2023 Change,Historical Life Expectancy 2023,Recovery from COVID-19
0,"Hong Kong, China",85.51,82.84,88.13,5.29,85.26,0.23,84.71,0.38,85.08,1.52,83.48,2.03,85.51,0.25
1,Japan,84.71,81.69,87.74,6.05,84.42,0.25,84.67,0.30,84.55,1.52,84.05,0.66,84.71,0.29
2,South Korea,84.33,81.19,87.16,5.96,83.69,0.23,83.67,0.18,83.85,1.52,82.73,1.60,84.33,0.64
3,French Polynesia,84.07,81.78,86.50,4.73,83.19,0.23,82.46,0.30,79.57,4.29,83.86,0.21,84.07,0.88
4,Andorra,84.04,82.10,86.11,4.01,84.10,0.23,79.42,2.91,82.33,1.69,84.02,0.03,84.04,−0.06

n\Cleaned df3:

,Country,2022 Life Expectancy All,2022 Male,2022 Female,2022 Sex Gap,Historical Life Expectancy 2014,2014 → 2019 Change,Historical Life Expectancy 2019,2019 → 2020 Change,Historical Life Expectancy 2020,2020 → 2021 Change,Historical Life Expectancy 2021,2021 → 2022 Change,Historical Life Expectancy 2022,Recovery from COVID-19
0,"Macao SAR, China",85.38,82.75,87.98,5.23,83.88,1.09,84.98,0.21,85.18,0.22,85.40,0.61,85.38,0.40
1,Japan,84.00,81.05,87.09,6.04,83.59,0.77,84.36,0.20,84.56,0.19,84.45,0.61,84.00,−0.36
2,"Hong Kong SAR, China",83.66,80.70,86.77,6.07,83.94,1.22,85.16,0.34,85.50,0.04,85.53,0.61,83.66,−1.49
3,French Polynesia,83.55,81.33,85.98,4.65,82.21,0.78,83.00,0.20,82.22,0.19,79.49,4.06,83.55,0.55
4,Switzerland,83.45,81.60,85.40,3.80,83.20,0.71,83.90,0.20,83.00,0.75,83.75,0.61,83.45,−0.45

n\Cleaned df5:

      Country  Life Expectancy All   Male  Female  Sex Gap
0      Monaco                89.60  85.70   93.49     7.79
1   Singapore                86.43  83.65   89.20     5.55
2       Macau                85.06  82.09   88.02     5.93
3       Japan                84.91  81.92   87.90     5.98
4  San Marino                83.86  81.30   86.65     5.35